name: rg_behavior_model
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  - pip=25.1.1
  - pandas==2.3.*
  - pip:
    - numpy==2.1.*
    - matplotlib==3.10.*
    - seaborn==0.13.*
    - navis==1.10.*
    - scikit-learn==1.7.*
    - scipy==1.15.*
    - sympy==1.14.*
    - python-dotenv==1.1.0
    - numba==0.61.2
    - h5py==3.14.0
    - tables==3.10.2
    - scikit-optimize
